version: '3.3'
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/cert:/etc/nginx/cert
      - /var/www/html:/var/www/html
    environment:
      - TZ=Asia/Shanghai
    networks:
      - my-network


  tvbot:
    build: ./
    container_name: tvbot
    ports:
      - '8080:8080'
    restart: unless-stopped
    command: ["uvicorn", "main:app", "--port", "8080"]
    networks:
      - my-network

    
networks:
  my-network:
    driver: bridge
  